# Generated by Django 3.0.3 on 2020-02-07 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='savingsgroup',
            name='created_date',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
