# Generated by Django 3.0.3 on 2020-02-08 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_savingsmember'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupFinancial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.IntegerField()),
                ('group_bal', models.FloatField()),
            ],
            options={
                'db_table': 'group_financial',
            },
        ),
    ]
